apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-todos
  name: dwk-todos-deploy
  labels:
    app: dwk-todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-todos
  template:
    metadata:
      labels:
        app: dwk-todos
    spec:
      containers:
      - name: dwk-todos
        image: bcerney/dwk-todos:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
      restartPolicy: Always
