apiVersion: v1
kind: Service
metadata:
  namespace: dwk-todos
  name: dwk-todos-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-todos
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000