apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-frontend-deploy
  labels:
    app: dwk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-frontend
  template:
    metadata:
      labels:
        app: dwk-frontend
    spec:
      # volumes:
      #   - name: flask-storage
      #     persistentVolumeClaim:
      #       claimName: flask-claim
      containers:
      - name: flask
        image: bcerney/dwk-frontend:latest
        imagePullPolicy: Always
        # volumeMounts:
        # - name: flask-storage
        #   mountPath: /app/files
        ports:
          - containerPort: 5000
      restartPolicy: Always
