apiVersion: batch/v1
kind: Job
metadata:
  name: db-backup-job
spec:
  template:
    spec:
      containers:
      - name: backup
        image: bcerney/db-backup-job
        env:
          - name: URL
            value: "postgres://postgres:example@postgres-svc.default:5432/postgres"
      restartPolicy: Never # This time we'll run it only once
